UNWIND [
  {char: 'Luke Skywalker', species: 'Human'},
  {char: 'Leia Organa', species: 'Human'},
  {char: 'Darth Vader', species: 'Human'},
  {char: 'Yoda', species: 'Yoda\'s species'},
  {char: 'Han Solo', species: 'Human'},
  {char: 'Chewbacca', species: 'Wookiee'},
  {char: 'Obi-Wan Kenobi', species: 'Human'},
  {char: 'Emperor Palpatine', species: 'Human'},
  {char: 'Anakin Skywalker', species: 'Human'},
  {char: 'Padmé Amidala', species: 'Human'},
  {char: 'Qui-Gon Jinn', species: 'Human'},
  {char: 'Mace Windu', species: 'Human'},
  {char: 'Jar Jar Binks', species: 'Gungan'},
  {char: 'Count Dooku', species: 'Human'},
  {char: 'Rey', species: 'Human'},
  {char: 'Finn', species: 'Human'},
  {char: 'Poe Dameron', species: 'Human'},
  {char: 'Kylo Ren', species: 'Human'},
  {char: 'BB-8', species: 'Droid'},
  {char: 'C-3PO', species: 'Droid'},
  {char: 'R2-D2', species: 'Droid'},
  {char: 'Lando Calrissian', species: 'Human'},
  {char: 'Boba Fett', species: 'Human'},
  {char: 'Jango Fett', species: 'Human'},
  {char: 'General Hux', species: 'Human'},
  {char: 'Rose Tico', species: 'Human'},
  {char: 'Aayla Secura', species: 'Twi\'lek'},
  {char: 'Admiral Ackbar', species: 'Mon Calamari'},
  {char: 'Admiral Piett', species: 'Human'},
  {char: 'Bail Organa', species: 'Human'},
  {char: 'Barriss Offee', species: 'Mirialan'},
  {char: 'Biggs Darklighter', species: 'Human'},
  {char: 'Bib Fortuna', species: 'Twi\'lek'},
  {char: 'Bossk', species: 'Trandoshan'},
  {char: 'Captain Phasma', species: 'Human'},
  {char: 'Chirrut Îmwe', species: 'Human'},
  {char: 'Dengar', species: 'Human'},
  {char: 'Greedo', species: 'Rodian'},
  {char: 'Hera Syndulla', species: 'Twi\'lek'},
  {char: 'Jabba the Hutt', species: 'Hutt'},
  {char: 'Kanan Jarrus', species: 'Human'},
  {char: 'Kit Fisto', species: 'Nautolan'},
  {char: 'Lobot', species: 'Human'},
  {char: 'Mon Mothma', species: 'Human'},
  {char: 'Nien Nunb', species: 'Sullustan'},
  {char: 'Plo Koon', species: 'Kel Dor'},
  {char: 'Saw Gerrera', species: 'Human'},
  {char: 'Sebulba', species: 'Dug'},
  {char: 'Shaak Ti', species: 'Togruta'},
  {char: 'Shmi Skywalker', species: 'Human'},
  {char: 'Wedge Antilles', species: 'Human'},
  {char: 'Wicket W. Warrick', species: 'Ewok'},
  {char: 'Zam Wesell', species: 'Clawdite'},
  {char: 'Ahsoka Tano', species: 'Togruta'},
  {char: 'Asajj Ventress', species: 'Dathomirian'},
  {char: 'Cad Bane', species: 'Duros'},
  {char: 'Captain Rex', species: 'Human'},
  {char: 'Savage Opress', species: 'Dathomirian'},
  {char: 'Hondo Ohnaka', species: 'Weequay'},
  {char: 'Pong Krell', species: 'Besalisk'},
  {char: 'Mother Talzin', species: 'Dathomirian'},
  {char: 'Ezra Bridger', species: 'Human'},
  {char: 'Sabine Wren', species: 'Human'},
  {char: 'Kallus', species: 'Human'},
  {char: 'Grand Admiral Thrawn', species: 'Chiss'},
  {char: 'Jyn Erso', species: 'Human'},
  {char: 'Cassian Andor', species: 'Human'},
  {char: 'Orson Krennic', species: 'Human'},
  {char: 'Bodhi Rook', species: 'Human'},
  {char: 'Baze Malbus', species: 'Human'},
  {char: 'Galen Erso', species: 'Human'},
  {char: 'Admiral Raddus', species: 'Mon Calamari'},
  {char: 'Dryden Vos', species: 'Human'},
  {char: 'Qi\'ra', species: 'Human'},
  {char: 'Enfys Nest', species: 'Human'},
  {char: 'L3-37', species: 'Droid'},
  {char: 'Beckett', species: 'Human'},
  {char: 'Val', species: 'Human'},
  {char: 'Rio Durant', species: 'Ardennian'}
] AS pair
MATCH (c:Character {name: pair.char})
MATCH (s:Species {name: pair.species})
CREATE (c)-[:IS_SPECIES]->(s);