UNWIND [
  {name: 'Tatooine', diameter: 10465, rotation_period: 23, orbital_period: 304, surface_water: 1, gravity: '1 standard', population: 200000, climate: 'arid', terrain: 'desert'},
  {name: 'Alderaan', diameter: 12500, rotation_period: 24, orbital_period: 364, surface_water: 40, gravity: '1 standard', population: 2000000000, climate: 'temperate', terrain: 'grasslands, mountains'},
  {name: 'Naboo', diameter: 12120, rotation_period: 26, orbital_period: 312, surface_water: 12, gravity: '1 standard', population: 4500000000, climate: 'temperate', terrain: 'grassy hills, swamps, forests, mountains'},
  {name: 'Stewjon', gravity: '1 standard', climate: 'temperate', terrain: 'grasslands, lakes'},
  {name: 'Corellia', diameter: 11000, rotation_period: 25, orbital_period: 329, surface_water: 70, gravity: '1 standard', population: 3000000000, climate: 'temperate', terrain: 'plains, urban, forests, hills'},
  {name: 'Kashyyyk', diameter: 12765, rotation_period: 26, orbital_period: 381, surface_water: 60, gravity: '1 standard', population: 45000000, climate: 'tropical', terrain: 'forests, jungles'},
  {name: 'Kamino', diameter: 19720, rotation_period: 27, orbital_period: 463, surface_water: 100, gravity: '1 standard', population: 1000000000, climate: 'temperate', terrain: 'ocean'},
  {name: 'Mon Cala', diameter: 11030, rotation_period: 21, orbital_period: 398, surface_water: 100, gravity: '1 standard', population: 27000000000, climate: 'temperate', terrain: 'oceans, islands, marshes'},
  {name: 'Geonosis', diameter: 11370, rotation_period: 30, orbital_period: 256, surface_water: 5, gravity: '0.9 standard', population: 100000000000, climate: 'temperate, arid', terrain: 'rock, desert, canyons, mesas'},
  {name: 'Jakku', rotation_period: 23, orbital_period: 298, surface_water: 8, gravity: '0.9 standard', climate: 'arid', terrain: 'deserts, mesas'},
  {name: 'Yavin 4', diameter: 10200, rotation_period: 24, orbital_period: 4818, surface_water: 8, gravity: '1 standard', population: 1000, climate: 'temperate, tropical', terrain: 'jungles, forests'},
  {name: 'Rodia', diameter: 7549, rotation_period: 29, orbital_period: 305, surface_water: 60, gravity: '1 standard', population: 1300000000, climate: 'tropical, humid', terrain: 'rainforests, oceans'},
  {name: 'Coruscant', diameter: 12240, rotation_period: 24, orbital_period: 365, surface_water: 0, gravity: '1 standard', population: 1000000000000, climate: 'temperate', terrain: 'urban'},
  {name: 'Alzoc III'},
  {name: 'Ardennia'},
  {name: 'Arkanis'},
  {name: 'Axxila'},
  {name: 'Bespin'},
  {name: 'Chad'},
  {name: 'Chandrila'},
  {name: 'Concord Dawn'},
  {name: 'Csilla'},
  {name: 'Dathomir'},
  {name: 'Dorin'},
  {name: 'Duro'},
  {name: 'Endor'},
  {name: 'Fest'},
  {name: 'Gamorr'},
  {name: 'Gentes'},
  {name: 'Glee Anselm'},
  {name: 'Grange'},
  {name: 'Haruun Kal'},
  {name: 'Hays Minor'},
  {name: 'Iridonia'},
  {name: 'Ithor'},
  {name: 'Jedha'},
  {name: 'Kintan'},
  {name: 'Klatooine'},
  {name: 'Lexrul'},
  {name: 'Lothal'},
  {name: 'Malastare'},
  {name: 'Mandalore'},
  {name: 'Mirial'},
  {name: 'Muunilinst'},
  {name: 'Nal Hutta'},
  {name: 'Ojom'},
  {name: 'Onderon'},
  {name: 'Parnassos'},
  {name: 'Ryloth'},
  {name: 'Serenno'},
  {name: 'Shili'},
  {name: 'Socorro'},
  {name: 'Sriluur'},
  {name: 'Sullust'},
  {name: 'Takodana'},
  {name: 'Toydaria'},
  {name: 'Trandosha'},
  {name: 'Vallt'},
  {name: 'Yarkora'},
  {name: 'Zolan'},
  {name: 'Zygerria'}
] AS props
CREATE (p:Planet) SET p = props;