UNWIND [
  {char: 'Luke Skywalker', planet: 'Tatooine'},
  {char: 'Leia Organa', planet: 'Alderaan'},
  {char: 'Darth Vader', planet: 'Tatooine'},
  {char: 'Han Solo', planet: 'Corellia'},
  {char: 'Chewbacca', planet: 'Kashyyyk'},
  {char: 'Obi-Wan Kenobi', planet: 'Stewjon'},
  {char: 'Emperor Palpatine', planet: 'Naboo'},
  {char: 'Anakin Skywalker', planet: 'Tatooine'},
  {char: 'Padmé Amidala', planet: 'Naboo'},
  {char: 'Qui-Gon Jinn', planet: 'Coruscant'},
  {char: 'Mace Windu', planet: 'Haruun Kal'},
  {char: 'Jar Jar Binks', planet: 'Naboo'},
  {char: 'Count Dooku', planet: 'Serenno'},
  {char: 'Rey', planet: 'Jakku'},
  {char: 'Poe Dameron', planet: 'Yavin 4'},
  {char: 'Kylo Ren', planet: 'Chandrila'},
  {char: 'C-3PO', planet: 'Tatooine'},
  {char: 'R2-D2', planet: 'Naboo'},
  {char: 'Lando Calrissian', planet: 'Socorro'},
  {char: 'Boba Fett', planet: 'Kamino'},
  {char: 'Jango Fett', planet: 'Concord Dawn'},
  {char: 'General Hux', planet: 'Arkanis'},
  {char: 'Rose Tico', planet: 'Hays Minor'},
  {char: 'Maz Kanata', planet: 'Takodana'},
  {char: 'Aayla Secura', planet: 'Ryloth'},
  {char: 'Admiral Ackbar', planet: 'Mon Cala'},
  {char: 'Admiral Piett', planet: 'Axxila'},
  {char: 'Bail Organa', planet: 'Alderaan'},
  {char: 'Barriss Offee', planet: 'Mirial'},
  {char: 'Biggs Darklighter', planet: 'Tatooine'},
  {char: 'Bib Fortuna', planet: 'Ryloth'},
  {char: 'Bossk', planet: 'Trandosha'},
  {char: 'Captain Phasma', planet: 'Parnassos'},
  {char: 'Chirrut Îmwe', planet: 'Jedha'},
  {char: 'Dengar', planet: 'Corellia'},
  {char: 'Greedo', planet: 'Rodia'},
  {char: 'Hera Syndulla', planet: 'Ryloth'},
  {char: 'Jabba the Hutt', planet: 'Nal Hutta'},
  {char: 'Kanan Jarrus', planet: 'Coruscant'},
  {char: 'Kit Fisto', planet: 'Glee Anselm'},
  {char: 'Lobot', planet: 'Bespin'},
  {char: 'Mon Mothma', planet: 'Chandrila'},
  {char: 'Nien Nunb', planet: 'Sullust'},
  {char: 'Plo Koon', planet: 'Dorin'},
  {char: 'Saw Gerrera', planet: 'Onderon'},
  {char: 'Sebulba', planet: 'Malastare'},
  {char: 'Shaak Ti', planet: 'Shili'},
  {char: 'Shmi Skywalker', planet: 'Tatooine'},
  {char: 'Wedge Antilles', planet: 'Corellia'},
  {char: 'Wicket W. Warrick', planet: 'Endor'},
  {char: 'Zam Wesell', planet: 'Zolan'},
  {char: 'Ahsoka Tano', planet: 'Shili'},
  {char: 'Asajj Ventress', planet: 'Dathomir'},
  {char: 'Cad Bane', planet: 'Duro'},
  {char: 'Captain Rex', planet: 'Kamino'},
  {char: 'Savage Opress', planet: 'Dathomir'},
  {char: 'Hondo Ohnaka', planet: 'Sriluur'},
  {char: 'Pong Krell', planet: 'Ojom'},
  {char: 'Mother Talzin', planet: 'Dathomir'},
  {char: 'Ezra Bridger', planet: 'Lothal'},
  {char: 'Sabine Wren', planet: 'Mandalore'},
  {char: 'Kallus', planet: 'Coruscant'},
  {char: 'Grand Admiral Thrawn', planet: 'Csilla'},
  {char: 'Jyn Erso', planet: 'Vallt'},
  {char: 'Cassian Andor', planet: 'Fest'},
  {char: 'Orson Krennic', planet: 'Lexrul'},
  {char: 'Bodhi Rook', planet: 'Jedha'},
  {char: 'Baze Malbus', planet: 'Jedha'},
  {char: 'Galen Erso', planet: 'Grange'},
  {char: 'Admiral Raddus', planet: 'Mon Cala'},
  {char: 'Dryden Vos', planet: 'Corellia'},
  {char: 'Qi\'ra', planet: 'Corellia'},
  {char: 'Beckett', planet: 'Glee Anselm'},
  {char: 'Rio Durant', planet: 'Ardennia'}
] AS pair
MATCH (c:Character {name: pair.char})
MATCH (p:Planet {name: pair.planet})
CREATE (c)-[:LIVES_ON]->(p);