UNWIND [
  {species: 'Wookiee', planet: 'Kashyyyk'},
  {species: 'Gungan', planet: 'Naboo'},
  {species: 'Twi\'lek', planet: 'Ryloth'},
  {species: 'Mon Calamari', planet: 'Mon Cala'},
  {species: 'Rodian', planet: 'Rodia'},
  {species: 'Trandoshan', planet: 'Trandosha'},
  {species: 'Kel Dor', planet: 'Dorin'},
  {species: 'Nautolan', planet: 'Glee Anselm'},
  {species: 'Togruta', planet: 'Shili'},
  {species: 'Hutt', planet: 'Nal Hutta'},
  {species: 'Zabrak', planet: 'Iridonia'},
  {species: 'Muun', planet: 'Muunilinst'},
  {species: 'Geonosian', planet: 'Geonosis'},
  {species: 'Chiss', planet: 'Csilla'},
  {species: 'Mirialan', planet: 'Mirial'},
  {species: 'Kaminoan', planet: 'Kamino'},
  {species: 'Chadra-Fan', planet: 'Chad'},
  {species: 'Dathomirian', planet: 'Dathomir'},
  {species: 'Duros', planet: 'Duro'},
  {species: 'Ewok', planet: 'Endor'},
  {species: 'Gamorrean', planet: 'Gamorr'},
  {species: 'Ithorian', planet: 'Ithor'},
  {species: 'Jawa', planet: 'Tatooine'},
  {species: 'Klatooinian', planet: 'Klatooine'},
  {species: 'Nikto', planet: 'Kintan'},
  {species: 'Quarren', planet: 'Mon Cala'},
  {species: 'Sullustan', planet: 'Sullust'},
  {species: 'Talz', planet: 'Alzoc III'},
  {species: 'Tusken Raider', planet: 'Tatooine'},
  {species: 'Ugnaught', planet: 'Gentes'},
  {species: 'Weequay', planet: 'Sriluur'},
  {species: 'Zygerrian', planet: 'Zygerria'},
  {species: 'Mandalorian', planet: 'Mandalore'},
  {species: 'Yarkora', planet: 'Yarkora'},
  {species: 'Toydarian', planet: 'Toydaria'}
] AS pair
MATCH (s:Species {name: pair.species})
MATCH (p:Planet {name: pair.planet})
CREATE (s)-[:HOMEWORLD]->(p);