UNWIND [
  {name: 'Human', classification: 'Mammal', designation: 'Sentient', average_height: 1.8, skin_colors: 'Light, Dark', hair_colors: 'Various', eye_colors: 'Various', average_lifespan: 79, language: 'Galactic Basic', homeworld: 'Various'},
  {name: 'Yoda\'s species', classification: 'Unknown', designation: 'Sentient', average_height: 0.66, skin_colors: 'Green', hair_colors: 'White', eye_colors: 'Brown', average_lifespan: 900, language: 'Galactic Basic', homeworld: 'Unknown'},
  {name: 'Wookiee', classification: 'Mammal', designation: 'Sentient', average_height: 2.28, skin_colors: 'Brown', hair_colors: 'Brown', eye_colors: 'Blue', average_lifespan: 400, language: 'Shyriiwook', homeworld: 'Kashyyyk'},
  {name: 'Gungan', classification: 'Amphibian', designation: 'Sentient', average_height: 1.96, skin_colors: 'Orange', eye_colors: 'Orange', average_lifespan: 70, language: 'Gungan', homeworld: 'Naboo'},
  {name: 'Twi\'lek', classification: 'Mammal', designation: 'Sentient', average_height: 1.8, skin_colors: 'Blue, Green, Red, Yellow', eye_colors: 'Various', average_lifespan: 80, language: 'Twi\'leki', homeworld: 'Ryloth'},
  {name: 'Mon Calamari', classification: 'Amphibian', designation: 'Sentient', average_height: 1.7, skin_colors: 'Orange', eye_colors: 'Red', average_lifespan: 70, language: 'Mon Calamarian', homeworld: 'Mon Cala'},
  {name: 'Rodian', classification: 'Reptilian', designation: 'Sentient', average_height: 1.7, skin_colors: 'Green', eye_colors: 'Black', average_lifespan: 78, language: 'Rodese', homeworld: 'Rodia'},
  {name: 'Droid', classification: 'Artificial', designation: 'Non-sentient', skin_colors: 'Various', eye_colors: 'Various', language: 'Binary'},
  {name: 'Trandoshan', classification: 'Reptilian', designation: 'Sentient', average_height: 2, skin_colors: 'Green', eye_colors: 'Red', average_lifespan: 70, language: 'Dosh', homeworld: 'Trandosha'},
  {name: 'Kel Dor', classification: 'Mammal', designation: 'Sentient', average_height: 1.88, skin_colors: 'Orange', eye_colors: 'Black', average_lifespan: 70, language: 'Kel Dor', homeworld: 'Dorin'},
  {name: 'Nautolan', classification: 'Amphibian', designation: 'Sentient', average_height: 1.96, skin_colors: 'Green', eye_colors: 'Black', average_lifespan: 80, language: 'Nautila', homeworld: 'Glee Anselm'},
  {name: 'Togruta', classification: 'Mammal', designation: 'Sentient', average_height: 1.8, skin_colors: 'Red', eye_colors: 'Blue', average_lifespan: 94, language: 'Togruti', homeworld: 'Shili'},
  {name: 'Hutt', classification: 'Gastropod', designation: 'Sentient', average_height: 3.9, skin_colors: 'Green', eye_colors: 'Orange', average_lifespan: 1000, language: 'Huttese', homeworld: 'Nal Hutta'},
  {name: 'Zabrak', classification: 'Mammal', designation: 'Sentient', average_height: 1.8, skin_colors: 'Red', eye_colors: 'Yellow', average_lifespan: 80, language: 'Zabraki', homeworld: 'Iridonia'},
  {name: 'Muun', classification: 'Mammal', designation: 'Sentient', average_height: 2, skin_colors: 'Pale', eye_colors: 'Black', average_lifespan: 100, language: 'Muun', homeworld: 'Muunilinst'},
  {name: 'Geonosian', classification: 'Insectoid', designation: 'Sentient', average_height: 1.75, skin_colors: 'Brown', eye_colors: 'Red', average_lifespan: 90, language: 'Geonosian', homeworld: 'Geonosis'},
  {name: 'Chiss', classification: 'Mammal', designation: 'Sentient', average_height: 1.8, skin_colors: 'Blue', hair_colors: 'Blue-black', eye_colors: 'Red', average_lifespan: 80, language: 'Cheunh', homeworld: 'Csilla'},
  {name: 'Mirialan', classification: 'Mammal', designation: 'Sentient', average_height: 1.75, skin_colors: 'Green', hair_colors: 'Black', eye_colors: 'Blue', average_lifespan: 70, language: 'Mirialan', homeworld: 'Mirial'},
  {name: 'Kaminoan', classification: 'Amphibian', designation: 'Sentient', average_height: 2, skin_colors: 'Pale', eye_colors: 'Black', average_lifespan: 80, language: 'Kaminoan', homeworld: 'Kamino'},
  {name: 'Chadra-Fan', classification: 'Mammal', designation: 'Sentient', average_height: 1, skin_colors: 'Brown', hair_colors: 'Brown', eye_colors: 'Black', average_lifespan: 50, language: 'Chadrafan', homeworld: 'Chad'},
  {name: 'Dathomirian', classification: 'Hybrid', designation: 'Sentient', average_height: 1.7, skin_colors: 'Pale', eye_colors: 'Yellow', average_lifespan: 60, language: 'Paecian', homeworld: 'Dathomir'},
  {name: 'Duros', classification: 'Reptilian', designation: 'Sentient', average_height: 1.9, skin_colors: 'Blue', eye_colors: 'Red', average_lifespan: 70, language: 'Durese', homeworld: 'Duro'},
  {name: 'Ewok', classification: 'Mammal', designation: 'Sentient', average_height: 1, skin_colors: 'Brown', hair_colors: 'Brown', eye_colors: 'Brown', average_lifespan: 50, language: 'Ewokese', homeworld: 'Endor'},
  {name: 'Gamorrean', classification: 'Mammal', designation: 'Sentient', average_height: 1.8, skin_colors: 'Green', eye_colors: 'Red', average_lifespan: 45, language: 'Gamorrean', homeworld: 'Gamorr'},
  {name: 'Ithorian', classification: 'Mammal', designation: 'Sentient', average_height: 2, skin_colors: 'Brown', eye_colors: 'Black', average_lifespan: 85, language: 'Ithorese', homeworld: 'Ithor'},
  {name: 'Jawa', classification: 'Mammal', designation: 'Sentient', average_height: 1, skin_colors: 'Unknown', eye_colors: 'Yellow', average_lifespan: 80, language: 'Jawaese', homeworld: 'Tatooine'},
  {name: 'Klatooinian', classification: 'Reptilian', designation: 'Sentient', average_height: 1.8, skin_colors: 'Brown', eye_colors: 'Black', average_lifespan: 90, language: 'Klatooinian', homeworld: 'Klatooine'},
  {name: 'Nikto', classification: 'Reptilian', designation: 'Sentient', average_height: 1.8, skin_colors: 'Red', eye_colors: 'Black', average_lifespan: 68, language: 'Nikto', homeworld: 'Kintan'},
  {name: 'Quarren', classification: 'Amphibian', designation: 'Sentient', average_height: 1.8, skin_colors: 'Orange', eye_colors: 'Blue', average_lifespan: 79, language: 'Quarrenese', homeworld: 'Mon Cala'},
  {name: 'Sullustan', classification: 'Mammal', designation: 'Sentient', average_height: 1.6, skin_colors: 'Light', eye_colors: 'Black', average_lifespan: 70, language: 'Sullustese', homeworld: 'Sullust'},
  {name: 'Talz', classification: 'Mammal', designation: 'Sentient', average_height: 2, skin_colors: 'White', eye_colors: 'Blue', average_lifespan: 60, language: 'Talzzi', homeworld: 'Alzoc III'},
  {name: 'Tusken Raider', classification: 'Mammal', designation: 'Sentient', average_height: 1.8, skin_colors: 'Unknown', hair_colors: 'Unknown', eye_colors: 'Unknown', average_lifespan: 70, language: 'Tusken', homeworld: 'Tatooine'},
  {name: 'Ugnaught', classification: 'Mammal', designation: 'Sentient', average_height: 1, skin_colors: 'Pink', eye_colors: 'Black', average_lifespan: 200, language: 'Ugnaught', homeworld: 'Gentes'},
  {name: 'Weequay', classification: 'Mammal', designation: 'Sentient', average_height: 1.7, skin_colors: 'Brown', hair_colors: 'Brown', eye_colors: 'Black', average_lifespan: 91, language: 'Weequay', homeworld: 'Sriluur'},
  {name: 'Zygerrian', classification: 'Mammal', designation: 'Sentient', average_height: 1.8, skin_colors: 'Tan', eye_colors: 'Blue', average_lifespan: 85, language: 'Zygerrian', homeworld: 'Zygerria'},
  {name: 'Jedi', classification: 'Mammal', designation: 'Sentient', average_height: 1.8, skin_colors: 'Various', hair_colors: 'Various', eye_colors: 'Various', average_lifespan: 120, language: 'Galactic Basic', homeworld: 'Various'},
  {name: 'Mandalorian', classification: 'Mammal', designation: 'Sentient', average_height: 1.8, skin_colors: 'Various', hair_colors: 'Various', eye_colors: 'Various', average_lifespan: 80, language: 'Mando\'a', homeworld: 'Mandalore'},
  {name: 'Yarkora', classification: 'Mammal', designation: 'Sentient', average_height: 2, skin_colors: 'White', eye_colors: 'Black', average_lifespan: 200, language: 'Yarkoran', homeworld: 'Yarkora'},
  {name: 'Toydarian', classification: 'Mammal', designation: 'Sentient', average_height: 1.2, skin_colors: 'Blue, Green', eye_colors: 'Yellow', average_lifespan: 91, language: 'Toydarian', homeworld: 'Toydaria'},
  {name: 'Ardennian'},
  {name: 'Besalisk'},
  {name: 'Clawdite'},
  {name: 'Dug'}
] AS props
CREATE (s:Species) SET s = props;